pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
stage('Test') {
    steps {
        bat 'mvn test'
    }
}
        stage('Complete')
        step{
            echo ' completed the build and  test the job'
        }
    }
}
