pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
stage('Test') {
    steps {
        bat 'mvn test'
    }
}
        stage('COmplete') {
    steps {
        echo 'Completed the build and test the job'
    }
}
    }
}
